language: go

go:
  - 1.13.x

notifications:
  email: false

before_script:
  - sudo apt-get -q install ruby
  - gem install bundler
  - bundle install

script:
  - bundle exec rspec
  - go test ./cmd
